# Nombre del archivo principal de streamlit
APP = main.py

# Comando para ejecutar Streamlit
run:
	streamlit run $(APP)

# Instalar las dependencias del proyecto desde requirements.txt
install:
	pip install -r requirements_dashboard.txt
